# -*- coding: utf-8 -*-
"""Assignment2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1osKkORzob4ZTW8yVvQAlcYTp3EqcIdjv
"""

import random as rd

sample_data = 500000
print("The first removed ball is white.")
print("After the first ball is removed, we have in total only 6 balls out of which 3 are red and 3 are white.")
print()
list_of_balls = [1, 1, 1, 1, 1, 1]

i=0
while i<3:
  temp = rd.randint(0, 5)
  if(list_of_balls[temp] == 1):
    list_of_balls[temp] = 0
    i+=1
red_count = white_count = 0 

for i in range(sample_data):
  temp = rd.randint(0, 5)
  if(list_of_balls[temp] == 0):
    white_count += 1
  else:
    red_count += 1
prob_red = red_count / sample_data

print("Result obtained from the simulation")
print("Probability that the second removed ball is red when the first removed ball is white is: {}".format(prob_red))
print()
print("Which is very very close to ")
print()
print("Result obtained theoretically")
print("Probability that the second removed ball is red when the first removed ball is white is: 0.5")

