# -*- coding: utf-8 -*-
"""Assignment4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dbFMJGLTBuIUWxRaJ6dEYRCk_wOWueJX
"""

import random as rd

len = 100000
count = 0

for i in range(len):
     x = rd.randint(1,6)
     y = rd.randint(1,6)
     z = x + y 
     if z == 8:
        count+=1
     if z == 9:
        count+=1 

prob = 1 - (count / len)  

print("Simulated value of probability = ",prob)
print(" Which is very very close to ")
print("Theoritical value of probability = 0.75")